package com.brandon3055.madhelp;

import com.brandon3055.brandonscore.BrandonsCore;
import com.brandon3055.madhelp.handlers.ConfigHandler;
import com.brandon3055.madhelp.handlers.ContentHandler;
import com.brandon3055.madhelp.handlers.ForgeEventHandler;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkCheckHandler;
import net.minecraftforge.fml.relauncher.Side;

import java.util.Arrays;
import java.util.Map;

@Mod(modid = com.brandon3055.madhelp.MadHelp.MODID, version = com.brandon3055.madhelp.MadHelp.VERSION, name = com.brandon3055.madhelp.MadHelp.MODNAME, dependencies = "required-after:brandonscore@[" + BrandonsCore.VERSION + ",);")
public class MadHelp {
    public static final String MODNAME = "Mad Help";
    public static final String MODID = "madhelp";
    public static final String VERSION = "${mod_version}";
    public static final String SELECT = "\u00A7";

    public MadHelp() {
        LogHelper.info("Hello Minecraft!!!");
    }

    @NetworkCheckHandler
    public boolean networkCheck(Map<String, String> map, Side side) {
        return true;
    }

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        ConfigHandler.init(event);
        MinecraftForge.EVENT_BUS.register(new ForgeEventHandler());
        ContentHandler.init();

        event.getModMetadata().autogenerated = false;
        event.getModMetadata().credits = "GreatOrator for requesting this mod be created";
        event.getModMetadata().description = "Minecraft map installer and more! This is a mod designed for mpd pack makers. Its primary feature is the ability to download and install minecraft maps selected by the pack creator.";
        event.getModMetadata().authorList = Arrays.asList("brandon3055");
        event.getModMetadata().logoFile = "";
        event.getModMetadata().url = "";
        event.getModMetadata().version = VERSION + "-MC1.12.2";
    }
}
